#!/usr/bin/env python3

import sys

import numpy as np
import matplotlib.pyplot as plt

from cc_pathlib import Path

from pathpatrol.layer import Layer

if __name__ == "__main__" :

	pth = Path(sys.argv[1]).resolve()

	if pth.suffix != '.png' :
		raise ValueError

	u = Layer().load_rastermap(pth)

	pth.with_suffix('.json').save(u.to_json())

	# print(u.g_lst[0].orig.p_arr[u.g_lst[0].o_arr])

	plt.figure()
	plt.plot(u.g_lst[0].orig.x_arr, u.g_lst[0].orig.y_arr, '+--')
	plt.plot(u.g_lst[0].convex.x_arr, u.g_lst[0].convex.y_arr, 'x-')
	plt.plot(u.g_lst[0].orig.p_arr[u.g_lst[0].o_arr,0], u.g_lst[0].orig.p_arr[u.g_lst[0].o_arr,1], 'o')
	for a, b in u.g_lst[0].concave :
		A = u.g_lst[0].orig[a]
		B = u.g_lst[0].orig[b]
		plt.plot([A[0], B[0]], [A[1], B[1]], 'v', color="tab:red")
	plt.grid()
	plt.axis("equal")
	plt.show()

	
	# plt.figure()
	# u.plot()
	# plt.show()
