#!/usr/bin/env python3

import sys

import numpy as np
import matplotlib.pyplot as plt

from cc_pathlib import Path

import base64

if __name__ == '__main__' :
	pth = Path(sys.argv[1]).resolve()

	dat = pth.read_bytes()
	txt = base64.a85encode(dat, wrapcol=64).decode('ascii')

	pth.with_suffix('.a85').write_text(txt)
	