#!/usr/bin/env python3

import sys

import numpy as np
import matplotlib.pyplot as plt

from cc_pathlib import Path

import base64

if __name__ == '__main__' :
	pth = Path(sys.argv[1]).resolve()

	a85 = pth.read_bytes()
	png = base64.a85decode(a85)

	pth.with_suffix('.png').write_bytes(png)
	